AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: myfirestore
      Runtime: go1.x
      CodeUri: ./
      Timeout: 5
      Environment:
        Variables:
          SLACK_TOKEN: hogehoge
          CHANNEL_ID: xxxxx